name: Build and Push Docker Image

# This workflow will run when you push to the main branch or trigger it manually
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Use a virtual machine with Ubuntu

    steps:
      # Step 1: Checkout the code from your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17 environment for Maven build
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Use Maven to build the Spring Boot application (creates target/*.jar)
      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      # Step 4: Authenticate (login) to GitHub Container Registry using GitHub token
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 5: Build and Push Docker image to GHCR (GitHub Container Registry)
      - name: Build and Push Docker image
        run: |
          OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/app1:latest"
          docker build -t $IMAGE_NAME .  # Build the Docker image with the correct tag
          docker push $IMAGE_NAME       # Push the Docker image to GitHub Container Registry
